import type { jsPDF } from "jspdf";

export interface PdfFooterOptions {
  generatedAt: string;
  generatedBy: string;
  tenantId?: string;
}

export const drawPdfFooter = (
  doc: jsPDF,
  pageNumber: number,
  pageCount: number,
  options: PdfFooterOptions
) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setDrawColor(220, 226, 233);
  doc.line(14, pageHeight - 18, pageWidth - 14, pageHeight - 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(90, 101, 115);

  const footerLeft = `Generated by: ${options.generatedBy} | Tenant: ${options.tenantId ?? "N/A"} | ${options.generatedAt}`;
  doc.text(footerLeft, 14, pageHeight - 11);
  doc.text(`Page ${pageNumber} of ${pageCount}`, pageWidth - 14, pageHeight - 11, {
    align: "right",
  });
};
